name: Java CI with Gradle
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
env:
  SAMPLE_PATH: Server/
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v2  # github action 버전 지정(major version)

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
          
      # Gradle wrapper 파일 실행 권한주기
      - name: Grant execute permission for gradlew
        working-directory: ${{ env.SAMPLE_PATH }}
        run: chmod +x gradlew
        
      - name: Build project
        working-directory: ${{ env.SAMPLE_PATH }}
        run: ./gradlew build -x test # 실제 application build(-x 옵션을 통해 test는 제외)
        
      - name: Test project
        working-directory: ${{ env.SAMPLE_PATH }}
        run: ./gradlew test
        
      - name: Publish Unit Test Results # test 후 result를 보기 위해 추가
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: ${{ always() }} # test가 실패해도 report를 남기기 위해 설정
        with:
          files: ${{ env.SAMPLE_PATH }}/build/test-results/**/*.xml
